### ISSUE TITLE
Unresolved packages for Windosw 64bit 2019.07 version of Anaconda

### ISSUE THREAD

**Issue by jnow** [fablabbcn/smartcitizen-data#1]
Hi,
just installed Anaconda on W64-bit system (https://repo.anaconda.com/archive/Anaconda3-2019.07-Windows-x86_64.exe)
`conda env create -f environment.yml` failes due to 
> ResolvePackageNotFound: 
> - xgboost=0.90
> - tzwhere=3.0

Installation of both packages seems not possible as there is a conflict between the dependencies of the files. xgboost is not available for W64, only py-xgboost.

**Comment by oscgonfer** [comment]
Hi @jnow 

Thanks for posting this.

You are right. xgboost is used as part of an anomaly detection algorithm that is not a core component of the framework. The best in this case is to delete this line in the environment.yml. Then, you can either follow the installation instructions from [here](https://pypi.org/project/xgboost/) if you need it. I will leave a note on the README for Windows users.

Regarding tzwhere, probably it has to do with the conda package manager (vs. pip). Can you try this at the end of the environment.yml and post the output?

```
  - yaml=0.1.*
  - pip:
    - termcolor==1.1.0
    - tzwhere=3.*
```
Thanks!

**Comment by oscgonfer** [comment]
Not using anaconda anymore. Closing this.
